import { DEFAULT_TERMINAL_HIGHLIGHT_RULES } from '../../lib/terminal-highlight/rules'
import type { SettingsState } from './types'

export const DEFAULTS: SettingsState = {
  language: 'zh-CN',
  theme: 'auto',
  uiFontFamily: ['system'],
  uiZoom: 100,
  middleClickCloseTab: false,
  editorLineEnding: 'lf',
  enableAnimation: true,
  showRealtimeInfo: true,
  tabCloseButtonLeft: true,
  fontLigatures: false,
  tabCloseConfirm: true,
  tabFlashNotify: true,
  tabMultiLine: false,
  updateChannel: 'stable',
  editorFontFamily: ['JetBrainsMono'],
  editorFontSize: 14,
  editorWordWrap: true,
  editorTabMode: 'four-spaces',
  lockOnStart: false,
  lockPassword: '',
  idleLockMinutes: 0,
  restoreSession: false,
  connectionTimeout: 30,
  heartbeatInterval: 60,
  defaultEncoding: 'utf-8',
  defaultPort: 22,
  autoReconnect: true,
  reconnectCount: 3,
  reconnectInterval: 5,
  termThemeLight: 'default-light',
  termThemeDark: 'default-dark',
  termCursorStyle: 'bar',
  termCursorBlink: true,
  termFontFamily: ['JetBrainsMono'],
  termFontSize: 14,
  termLineHeight: 1,
  termLetterSpacing: 0,
  termZoomEnabled: true,
  termStripeEnabled: false,
  termHighlightRules: DEFAULT_TERMINAL_HIGHLIGHT_RULES.map((rule) => ({ ...rule })),
  activeProfileId: '__default__',
  termHighlightEnhance: true,
  sshSftpPathSync: true,
  termSelectAutoCopy: false,
  termCommandHint: true,
  termSuggestionMode: 'smart',
  termSuggestionSources: ['history', 'snippet', 'command-spec'],
  sshHistoryEnabled: true,
  sshHistoryStorage: 'local',
  sshHistoryLoadCount: 100,
  termHighPerformance: true,
  termMiddleClickAction: 'none',
  termRightClickAction: 'menu',
  termSound: false,
  termCtrlVPaste: true,
  termScrollback: 1000,
  termLogDir: '',
  sftpDefaultEditor: 'builtin',
  sftpParentDirClick: false,
  sftpFileListLayout: 'horizontal',
  sftpListTimeout: 60,
  sftpDefaultSavePath: '',
  sftpDoubleClickAction: 'auto',
  sftpShowHidden: false,
  dbTableFont: ['JetBrainsMono'],
  dbAutoExpand: true,
  dbShowPrimaryKey: true,
  dbCalcTotalRows: false,
  dbCompositeHeader: false,
  dbLoadAllFields: false,
  dbTextAlign: 'auto',
  dbRowsPerPage: 500,
  dbDangerSqlConfirm: true,
  dbSqlStopOnError: false,
  dbScrollMode: 'natural',
  dbCursorScrollSpeed: 1,
  redisMaxLoadCount: 10000,
  redisGroupSeparator: ':',
  redisShowValue: false,
  hideEmptyFolders: false,
  syncRepoSource: 'local',
  syncAutoSync: false,
  syncCheckInterval: 15,
  syncEncryptionKey: '',
  syncTlsVerify: true,
  syncLocalPath: '',
  syncGitUrl: '',
  syncGitBranch: '',
  syncGitPath: '',
  syncGitUsername: '',
  syncGitPassword: '',
  syncGitSshKey: '',
  syncGitSshKeyLabel: '',
  syncGitSshKeyMode: 'manager',
  syncWebdavEndpoint: '',
  syncWebdavPath: 'vortix',
  syncWebdavUsername: '',
  syncWebdavPassword: '',
  syncS3Style: 'virtual-hosted',
  syncS3Endpoint: 'https://s3.amazonaws.com',
  syncS3Path: 'vortix',
  syncS3Region: 'ap-east-1',
  syncS3Bucket: '',
  syncS3AccessKey: '',
  syncS3SecretKey: '',
  debugMode: false,
}

export const FONT_KEYS = ['uiFontFamily', 'editorFontFamily', 'termFontFamily', 'dbTableFont'] as const
export const TERM_APPEARANCE_KEYS: (keyof SettingsState)[] = [
  'termThemeLight',
  'termThemeDark',
  'termCursorStyle',
  'termCursorBlink',
  'termFontFamily',
  'termFontSize',
  'termLineHeight',
  'termLetterSpacing',
  'termScrollback',
  'termHighlightRules',
  'activeProfileId',
]
