import type {
  AdvancedSettings,
  AuthType,
  EnvEntry,
  ProxyType,
  SshConfigState,
  SshConfigTab,
  SubModalKey,
  TunnelEntry,
} from './types'

export const defaultAdvanced: AdvancedSettings = {
  sftp: true,
  lrzsz: true,
  trzsz: true,
  sftpSudo: false,
  x11: false,
  terminalEnhance: false,
  pureTerminal: false,
  recordLog: false,
  x11Display: 'localhost:0.0',
  sftpCommand: 'sudo -S /usr/lib/openssh/sftp-server',
  heartbeat: '0',
  connectTimeout: '15',
  encoding: 'UTF-8',
  terminalType: 'xterm-256color',
  sftpDefaultPath: '',
  expireDate: '',
  initCommand: '',
}

export const defaultSubModals: Record<SubModalKey, boolean> = {
  selectKey: false,
  importKey: false,
  selectPreset: false,
  managePreset: false,
  editTunnel: false,
  selectAsset: false,
}

export const initialState = {
  activeTab: '标准' as SshConfigTab,
  colorTag: null as string | null,
  environment: '无',
  name: '',
  host: '',
  user: 'root',
  port: '22',
  authType: 'password' as AuthType,
  password: '',
  privateKeyId: null as string | null,
  privateKeyName: '',
  privateKeyPassword: '',
  mfaSecret: '',
  presetId: null as string | null,
  presetName: '',
  jumpKeyId: null as string | null,
  jumpKeyName: '',
  jumpKeyPassword: '',
  agentSocketPath: '',
  remark: '',
  tunnels: [] as TunnelEntry[],
  editingTunnel: null as TunnelEntry | null,
  proxyType: '关闭' as ProxyType,
  proxyHost: '127.0.0.1',
  proxyPort: '7890',
  proxyUsername: '',
  proxyPassword: '',
  proxyTimeout: '5',
  jumpServerId: null as string | null,
  jumpServerName: '',
  envVars: [] as EnvEntry[],
  selectedEnvIndex: null as number | null,
  advanced: { ...defaultAdvanced },
  subModals: { ...defaultSubModals },
  errors: {} as Record<string, string>,
  editingId: null as string | null,
  saving: false,
  loading: false,
  testing: false,
  testResult: null as { success: boolean; message: string } | null,
} satisfies Partial<SshConfigState>
