use crate::time_utils::now_timestamp;

pub(super) fn sanitize_filename(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '-' || ch == '_' || ch == '.' || ch == ' ' {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() {
        "key".to_string()
    } else {
        out
    }
}

pub(super) fn build_tar(files: &[(String, String)]) -> Vec<u8> {
    let mut blocks: Vec<u8> = Vec::new();
    for (name, content) in files {
        let content_bytes = content.as_bytes();
        let mut header = [0u8; 512];
        let name_bytes = name.as_bytes();
        let copy_len = name_bytes.len().min(100);
        header[..copy_len].copy_from_slice(&name_bytes[..copy_len]);
        write_octal(&mut header[100..108], 0o644, 8);
        write_octal(&mut header[108..116], 0, 8);
        write_octal(&mut header[116..124], 0, 8);
        write_octal(&mut header[124..136], content_bytes.len() as u64, 12);
        write_octal(&mut header[136..148], now_timestamp() as u64, 12);
        header[156] = b'0';
        header[257..263].copy_from_slice(b"ustar\0");
        header[263..265].copy_from_slice(b"00");
        for b in &mut header[148..156] {
            *b = b' ';
        }
        let checksum: u32 = header.iter().map(|b| *b as u32).sum();
        write_octal(&mut header[148..156], checksum as u64, 8);
        blocks.extend_from_slice(&header);
        blocks.extend_from_slice(content_bytes);
        let pad = 512 - (content_bytes.len() % 512);
        if pad < 512 {
            blocks.extend_from_slice(&vec![0u8; pad]);
        }
    }
    blocks.extend_from_slice(&[0u8; 1024]);
    blocks
}

fn write_octal(buf: &mut [u8], value: u64, width: usize) {
    let s = format!("{:0width$o}\0", value, width = width - 1);
    let bytes = s.as_bytes();
    let len = bytes.len().min(buf.len());
    buf[..len].copy_from_slice(&bytes[..len]);
}

pub(super) fn append_vortix_tag(public_key: &str) -> String {
    let trimmed = public_key.trim_end();
    if trimmed.starts_with("-----") {
        format!("{}\n# [Generated by Vortix]\n", trimmed)
    } else {
        format!("{} [Generated by Vortix]\n", trimmed)
    }
}
